name: Release the package on merge into main

# Only trigger when a pull request into main branch is closed.
on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  run-tests:
    if: "!contains(github.event.head_commit.message, 'skipci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install requirements
        run: pip install -r functions/event_handler/requirements.txt

      - name: Run tests
        env:
          BIGQUERY_EVENTS_TABLE: my-table
        run: python -m unittest

  release:
    # This job will only run if the PR has been merged (and not closed without merging).
    if: "github.event.pull_request.merged == true && !contains(github.event.pull_request.head.message, 'skipci')"
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get repo version
      run: echo "VERSION=$(python setup.py --version)" >> $GITHUB_ENV

    - name: Create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, no need to create your own.
      with:
        tag_name: ${{ env.VERSION }}
        release_name: ${{ github.event.pull_request.title }}
        body: ${{ github.event.pull_request.body }}
        draft: false
        prerelease: false
